#pragma once
#include "Order.h"
#include <map>
#include <deque>
#include <vector>
#include <optional>

class OrderBook {
public:
    // Returns any trades generated by this order
    std::vector<Trade> addOrder(Order order);
    bool cancelOrder(uint64_t orderId);

    void printBook() const;

private:
    // Bids: highest price first -> descending
    std::map<double, std::deque<Order>, std::greater<double>> bids;
    // Asks: lowest price first -> ascending
    std::map<double, std::deque<Order>> asks;

    // orderId -> (side, price) for cancel lookups
    std::unordered_map<uint64_t, std::pair<Side, double>> orderIndex;

    std::vector<Trade> matchOrder(Order& incoming);
};
